#!/bin/bash

setxkbmap -model pc104 -layout us,ru -option grp:caps_toggle

xss-lock --transfer-sleep-lock -n /use/lib/xsecurelock/dimmer -l -- {{ xsecurelock-command }} &
~/.screenlayout/default.sh &
pulseaudio --start &

{{#if (is_executable "nm-applet")~}}
nm-applet &
{{/if~}}

{{#if (is_executable "blueman-applet")~}}
blueman-applet &
{{/if~}}

{{#if  dotter.packages.hid-server~}}
if [ -z "$(pidof hid_server)" ]; then
    mv ~/.hid_server.current ~/.hid_server.previous
    sudo -E hid_server |& tee ~/.hid_server.current &
else
    echo "hid_server is already running"
fi
{{/if~}}

disown -a 