#!/bin/bash

export DISPLAY=":0"

{{#if xsecurelock-saver~}}
export XSECURELOCK_SAVER="$(which {{ xsecurelock-saver }})"
{{/if~}}

export XSECURELOCK_DIM_FPS=60
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_PASSWORD_PROMPT=hidden
export XSECURELOCK_PAM_SERVICE=xsecurelock

/usr/bin/xsecurelock
